info:
  build:
    artifact: '@project.artifactId@'
    description: '@project.description@'
    name: '@project.name@'
    version: '@project.version@'
server:
  port: 9026

management:
  security:
    enabled: true
endpoints:
  shutdown:
    enabled: false
  prometheus:
    sensitive: false
  sensitive: true

spring:
  profiles:
    active: ${fro_env:bnb}-${active:dev}
  kafka:
    topic: prometheus
    consumer:
      group-id: default_group
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 1000

